import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import type { SemanticVariableName } from "../src/semantic.js"
import { semanticDarkVars, semanticLightVars } from "../src/semantic.js"

const rootDir = dirname(fileURLToPath(import.meta.url))

function block(
  selector: string,
  entries: ReadonlyArray<readonly [string, string]>
): string {
  const lines = [...entries].map(([k, v]) => `    --${k}: ${v};`)
  return `${selector} {\n${lines.join("\n")}\n}\n`
}

const lightEntries = (
  Object.keys(semanticLightVars) as SemanticVariableName[]
).map((k) => [k, semanticLightVars[k]] as const)

const darkEntries = (
  Object.keys(semanticDarkVars) as (keyof typeof semanticDarkVars)[]
).map((k) => [k, semanticDarkVars[k] as string] as const)

const header = `/* Generated by scripts/generate-semantic-css.ts from src/semantic.ts — do not edit by hand */\n`

const css =
  header +
  "\n" +
  block(":root", lightEntries) +
  "\n" +
  block(".dark", darkEntries)

const outFile = join(rootDir, "../src/generated/semantic-variables.css")
mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(outFile, css, "utf8")

console.warn(`wrote ${outFile}`)
