import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import type { PublicVariableName } from "../src/public.js"
import { publicDarkVars, publicLightVars } from "../src/public.js"

const rootDir = dirname(fileURLToPath(import.meta.url))

function block(
  selector: string,
  entries: ReadonlyArray<readonly [string, string]>,
): string {
  const lines = [...entries].map(([k, v]) => `    --${k}: ${v};`)
  return `${selector} {\n${lines.join("\n")}\n}\n`
}

const lightEntries = (
  Object.keys(publicLightVars) as PublicVariableName[]
).map((k) => [k, publicLightVars[k]] as const)

const darkEntries = (
  Object.keys(publicDarkVars) as (keyof typeof publicDarkVars)[]
).map((k) => [k, publicDarkVars[k] as string] as const)

const header = `/* Generated by scripts/generate-public-css.ts from src/public.ts — do not edit by hand */\n`

const css =
  header +
  "\n" +
  block(".public-theme", lightEntries) +
  "\n" +
  block(".dark .public-theme, .public-theme.dark", darkEntries)

const outFile = join(rootDir, "../src/generated/public-variables.css")
mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(outFile, css, "utf8")

console.warn(`wrote ${outFile}`)
