import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import type { CeremonyVariableName } from "../src/ceremony.js"
import { ceremonyDarkVars, ceremonyLightVars } from "../src/ceremony.js"

const rootDir = dirname(fileURLToPath(import.meta.url))

function block(
  selector: string,
  entries: ReadonlyArray<readonly [string, string]>,
): string {
  const lines = [...entries].map(([k, v]) => `    --${k}: ${v};`)
  return `${selector} {\n${lines.join("\n")}\n}\n`
}

const lightEntries = (
  Object.keys(ceremonyLightVars) as CeremonyVariableName[]
).map((k) => [k, ceremonyLightVars[k]] as const)

const darkEntries = (
  Object.keys(ceremonyDarkVars) as (keyof typeof ceremonyDarkVars)[]
).map((k) => [k, ceremonyDarkVars[k] as string] as const)

const header = `/* Generated by scripts/generate-ceremony-css.ts from src/ceremony.ts — do not edit by hand */\n`

const css =
  header +
  "\n" +
  block(".ceremony-theme", lightEntries) +
  "\n" +
  block(".dark .ceremony-theme, .ceremony-theme.dark", darkEntries)

const outFile = join(rootDir, "../src/generated/ceremony-variables.css")
mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(outFile, css, "utf8")

console.warn(`wrote ${outFile}`)
